### ISSUE TITLE
Not compatible with System.Reactive.Interfaces, Version=3.1.1

### ISSUE THREAD

**Issue by hrshitjain** [macro187/testrunner#10]
Test Runner gives exception when used with System.Reactive.Interfaces, Version=3.1.1. The exception stack trace gives information that it is looking for 'System.Reactive.Interfaces, Version=3.0.0.0".

**Comment by macro187** [comment]
Hi @hrshitjain 

TestRunner doesn't use `System.Reactive.Interfaces`.  Can you provide some more information please?  At a minimum 1) the error message(s) and stack trace you're getting, and 2) whether you're running on .NET Core or the full .NET framework.

Thanks,
Ron

**Comment by hrshitjain** [comment]
Stack Trace : 

An internal error occurred in TestRunner.exe:
Exception has been thrown by the target of an invocation.
Type: System.Reflection.TargetInvocationException
Source: mscorlib
StackTrace:
  at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
  at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
  at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
  at System.Activator.CreateInstance(Type type, Boolean nonPublic)
  at System.Activator.CreateInstance(Type type)
  at TestRunner.Program.Program.RunTest(TestMethod testMethod, MethodInfo testInitializeMethod, MethodInfo testCleanupMethod, TestClass testClass)
  at TestRunner.Program.Program.RunTestClass(TestClass testClass)
  at TestRunner.Program.Program.RunTestAssembly(String assemblyPath)
  at TestRunner.Program.Program.Main2(String[] args)
InnerException:
  Could not load file or assembly 'System.Reactive.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.
  Type: System.IO.FileNotFoundException
  Source: ReactiveProperty
  StackTrace:
    at Reactive.Bindings.ReactiveProperty`1..ctor(T initialValue, ReactivePropertyMode mode, IEqualityComparer`1 equalityComparer)
    at Reactive.Bindings.ReactiveProperty`1..ctor()
    at OnSolveMobile.ViewModels.Base.ViewModelBase..ctor(INavigationService navigationService, IAPIService apiService, IPageDialogService pageDialogService)
      in D:\OnSolveMobile\OnSolveMobile\OnSolveMobile\OnSolveMobile\ViewModels\Base\ViewModelBase.cs:line 45
    at OnSolveMobile.ViewModels.Home.HomePageViewModel..ctor(INavigationService navigationService, IAPIService apiService)
      in D:\OnSolveMobile\OnSolveMobile\OnSolveMobile\OnSolveMobile\ViewModels\Home\HomeViewModel.cs:line 14
    at OnSolveUnitTest.Tests.Home.HomePageTest..ctor()
      in D:\OnSolveMobile\OnSolveMobile\OnSolveUnitTest\Tests\Home\HomePageTest.cs:line 36

**Comment by hrshitjain** [comment]
Also, I am using Reactive property in my code against which i have written test cases. Reactive property uses System.Reactive.Interface assembly. I have System.Reactive.Interface (version 3.1.1) in my code but test runner is looking for 3.0.0.0 and thereby giving exception.

**Comment by macro187** [comment]
Hi @hrshitjain 

All TestRunner does is ask the .NET CLR to load your test assembly.  So it's just regular .NET class loading / binding going on, nothing TestRunner specific.

1) Maybe the System.Reactive.Interface dll isn't getting copied to the test project build output.  Is there *any* System.Reactive.Interface dll ending up in your test project's `bin\<configuration>` directory along with the test .dll?

2) Maybe your dll's are linked against different versions of the System.Reactive.Interface dll.  Are all your projects building against the same version of the System.Reactive.Interface NuGet package?  Visual Studio has a nice UI for checking this under Tools -> NuGet Package Manager -> Manage NuGet Packages for Solution -> Consolidate

Regards,
Ron

**Comment by hrshitjain** [comment]
Hi @macro187 ,

1. The System.Reactive.Interface dll is getting copied to the test project build output.
2. My test project is targeting .Net Framework 4.6.1 and the code which I am testing is targeting .Net Standard 2.0.

So, if I install Reactive Property library on on my code project it is installed without any other dependency but in case of test project it is installed along with System.Reactive.* libraries.

**Comment by macro187** [comment]
What about your NuGet package versions?

**Comment by hrshitjain** [comment]
Test Runner - v1.5.1
ReactiveProperty - v4.2.1
System.Reactive.Interface -v3.1.1

**Comment by hrshitjain** [comment]
Yes it is same as v3.1.1.

Also, I am able to run the same project with other console runner.

**Comment by macro187** [comment]
Okay well I'm afraid I can't do much else for you.

The original error message is clear: `Could not load file or assembly 'System.Reactive.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies.`  So something in your solution is linked against System.Reactive.Interfaces 3.0.0.0.

If you have an assembly redirect in place that's enabling it to work in other console runners, it could be that TestRunner's config file switching code isn't good enough to pick it up.  I can't be sure though.  I'll create a separate issue to investigate this possibility.

Thanks for the report.
