### ISSUE TITLE
TestContext property getter(s) not working on .NET Core

### ISSUE THREAD

**Issue by macro187** [macro187/testrunner#11]
For some reason, .NET Core will not accept the dynamically generated `TestContext` overrides.  .NET Framework seems to accept them.

```
=============================================================================================
Assembly: testrunner.Tests.MSTest/bin/Debug/netcoreapp2.0/publish/testrunner.Tests.MSTest.dll
=============================================================================================

Test Assembly:
C:\p\testrunner\testrunner.Tests.MSTest\bin\Debug\netcoreapp2.0\publish\testrunner.Tests.MSTest.dll

[AssemblyInitialize] AssemblyInitialize()

An internal error occurred in testrunner.dll:
Method 'get_Properties' in type 'TestContextProxy' from assembly 'TestContextProxyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Type: System.TypeLoadException
Source: System.Private.CoreLib
StackTrace:
  at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
  at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
  at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
  at TestRunner.Domain.TestContextProxy.GetTypeFromTypeBuilder(TypeBuilder typeBuilder)
    in C:\p\testrunner\testrunner\Domain\TestContextProxy.cs:line 189
  at TestRunner.Domain.TestContextProxy.BuildProxy()
    in C:\p\testrunner\testrunner\Domain\TestContextProxy.cs:line 59
  at TestRunner.Domain.TestContextProxy.get_Proxy()
    in C:\p\testrunner\testrunner\Domain\TestContextProxy.cs:line 26
  at TestRunner.Program.Program.RunMethod(MethodInfo method, Object instance, Boolean takesTestContext, Type expectedException, Boolean expectedExceptionAllowDerived, String prefix)
    in C:\p\testrunner\testrunner\Program\Program.cs:line 509
  at TestRunner.Program.Program.RunTestAssembly(String assemblyPath)
    in C:\p\testrunner\testrunner\Program\Program.cs:line 198
  at TestRunner.Program.Program.Main2(String[] args)
    in C:\p\testrunner\testrunner\Program\Program.cs:line 59
```

**Comment by macro187** [comment]
Fixed
